nt main(int argc, char *argv[])
int main(int argc, __attribute__((unused)) char *argv[])
int main(int argc, char *argv[])
int main(int argc, char *argv[])
int isInteger(const char *s)
int main(int argc, char const *argv[])
